// One-off operational script: import the Night City Law Book into the Book of
// Laws (ncpd_laws). Idempotent — upserts by exact title, so re-running updates
// the body/sortOrder of an existing entry instead of creating duplicates.
//
// Usage (from repo root):
//   LAWBOOK_TARGET=dev  pnpm --filter @workspace/api-server exec tsx src/scripts/import-ncpd-lawbook.ts
//   LAWBOOK_TARGET=prod pnpm --filter @workspace/api-server exec tsx src/scripts/import-ncpd-lawbook.ts
//
// Targeting prod requires LIVE_PROD_DATABASE_URL and is refused otherwise.

export {};

const target = (process.env.LAWBOOK_TARGET ?? "").toLowerCase();
if (target === "prod") {
  if (!process.env.LIVE_PROD_DATABASE_URL) {
    console.error("LAWBOOK_TARGET=prod requires LIVE_PROD_DATABASE_URL; refusing to run.");
    process.exit(1);
  }
  process.env.DATABASE_URL = process.env.LIVE_PROD_DATABASE_URL;
} else if (target !== "dev") {
  console.error("Set LAWBOOK_TARGET=dev or prod");
  process.exit(1);
}

type LawEntry = { title: string; body: string };

// The full Night City Law Book, transcribed from the source document. Each
// NCMC section becomes one Book-of-Laws entry; subsections are rendered as
// markdown headings within the body.
const LAWS: LawEntry[] = [
  {
    title: "Night City Law Book — Overview",
    body: [
      "This is the Law Book of Night City, produced by Night Corp and the Night City Police Department (NCPD). It sets out what is legal in Night City and the three categories that crimes are sorted into: **Infractions**, **Misdemeanors**, and **Felonies**.",
      "",
      "**Recognized crimes include:**",
      "",
      "- TheNet offenses",
      "- Arson",
      "- Assault / Battery",
      "- Burglary / Robbery",
      "- Fake eddies / Counterfeiting (weapons, drugs, false IDs, etc.)",
      "- Possession of dead bodies",
      "- Disturbing the peace / Disorderly conduct",
      "- Espionage",
      "- Corporate fraud / Embezzlement",
      "- Non-corporate fraud / Embezzlement",
      "- Extortion",
      "- Grand theft auto",
      "- Kidnapping",
      "- Intellectual property infringement",
      "- Manslaughter",
      "- Murder",
      "- Rape",
      "- Obstruction of justice",
      "- Possession of an illegal weapon",
      "- Possession of illegal / stolen goods",
      "- Riot",
      "- Selling goods / services without a license",
      "- Smuggling",
      "- Terrorism",
      "- Traffic offenses (1st / 2nd / 3rd strike)",
      "- Trafficking",
      "- Trespassing",
      "- Vandalism",
    ].join("\n"),
  },
  {
    title: "NCMC Section 1 — Regulated Goods, Services, and Activities",
    body: [
      "**Section 1.01 — Purpose and Scope**",
      "",
      "Night City recognizes the legal manufacture, possession, sale, purchase, and personal use of various controlled goods and services, provided that all required permits, licenses, registrations, safety requirements, and age restrictions are followed.",
      "",
      "The legality of an item or activity does not remove the responsibility of the individual or business involved. Any person manufacturing, distributing, selling, purchasing, possessing, or using a regulated product must comply with all applicable Night City laws.",
      "",
      "The activities regulated under this part include:",
      "",
      "- Firearms and ammunition",
      "- Controlled drugs and narcotics",
      "- Braindances",
      "- Gambling and betting services",
      "- Sex work and adult services",
      "- Alcohol",
      "- Other controlled products or services designated by Night City authorities",
      "",
      "Operating without the required authorization may result in fines, confiscation of property, suspension of business operations, permit revocation, arrest, or criminal charges.",
      "",
      "**Section 1.02 — Identification and Year of Age Requirement**",
      "",
      "For the purposes of this code, Year of Age, abbreviated as YoA, refers to a person's legally recognized age.",
      "",
      "Night City recognizes several forms of identification:",
      "",
      "- **State Identification Number (SIN):** A government-issued identity number used to verify citizenship, age, legal status, and personal records.",
      "- **Corporate Identification Number (CIN):** A corporation-issued identity number used to verify employees, contractors, customers, or authorized persons under corporate systems.",
      "- **Temporary Identification Card (TIC):** A short-term identification document issued to individuals without a valid SIN, CIN, or other recognized identification record.",
      "",
      "Unless otherwise stated, a person must be at least 19 YoA to:",
      "",
      "- Purchase, possess, or consume alcohol",
      "- Purchase, possess, or use recreational drugs",
      "- Enter a licensed gambling establishment",
      "- Participate in commercial gambling",
      "- Purchase, access, or experience age-restricted Braindances",
      "- Purchase, access, or receive sexual services",
      "- Work in licensed sex work",
      "- Apply for certain commercial permits involving regulated goods",
      "",
      "Businesses are required to verify a customer's YoA through a valid SIN, CIN, TIC, biometric scan, personal data profile, or another approved identification record.",
      "",
      "Knowingly selling, providing, or allowing access to an age-restricted product or service to a person under 19 YoA is prohibited.",
      "",
      "Possession, use, presentation, alteration, duplication, or creation of a false SIN, CIN, TIC, or identification profile is prohibited.",
      "",
      "**Section 1.03 — Temporary Identification Card (TIC)**",
      "",
      "A Temporary Identification Card, abbreviated as TIC, is a short-term identification document issued to individuals who do not currently possess a valid SIN, CIN, or other recognized identification record.",
      "",
      "A TIC is a limited identification document and may only contain:",
      "",
      "- The individual's legal name or registered name",
      "- A unique temporary identification number",
      "- A thumbprint or approved biometric identifier",
      "",
      "A TIC does not establish citizenship, permanent legal status, employment status, ownership rights, or unrestricted access to regulated services.",
      "",
      "A TIC may be used for temporary identity verification when approved by Night City authorities, licensed businesses, or authorized service providers.",
      "",
      "All information stored on a TIC is temporary. After one month from the date of issuance, all personal information and identification data stored on the TIC will be automatically erased, and the card will become invalid unless renewed or replaced through an approved process.",
      "",
      "A person using an expired, altered, copied, stolen, or fraudulent TIC is subject to the same penalties as using a false identification document.",
      "",
      "Businesses accepting TICs must verify that the card is active, authentic, and has not passed its expiration period.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 2 — Firearms and Weapons",
    body: [
      "**Section 2.01 — Firearm Ownership and Carry Requirements**",
      "",
      "Firearms are legal to manufacture, possess, purchase, sell, and carry within Night City when all required laws and regulations are followed.",
      "",
      "Revolvers and semi-automatic pistols do not require a firearm license to carry. However, the owner must possess valid proof of purchase, ownership, or lawful acquisition of the weapon.",
      "",
      "Automatic firearms, heavy weapons, light machine guns (LMGs), armor-piercing (AP) weapons, and other restricted firearms require a firearm license to own or possess.",
      "",
      "Explosive weapons and explosive devices require a separate demolition license. A person may not manufacture, possess, store, or use explosive weapons without the proper authorization.",
      "",
      "A firearm license or proof of ownership does not authorize threats, intimidation, reckless behavior, unlawful violence, or criminal activity.",
      "",
      "**Section 2.02 — Open Carry Restrictions**",
      "",
      "Open carrying of firearms is generally permitted unless restricted by Night City law, local regulations, or private property rules.",
      "",
      "A person must obtain an open carry permit to openly carry weapons in restricted areas of the city.",
      "",
      "Restricted areas may include:",
      "",
      "- Government facilities",
      "- Police facilities",
      "- Medical facilities",
      "- Corporate restricted zones",
      "- Emergency response areas",
      "- Other locations designated by Night City authorities",
      "",
      "Private businesses and corporate properties may restrict or prohibit firearms on their premises.",
      "",
      "**Section 2.03 — Restricted Weapons**",
      "",
      "The following weapons require additional authorization or licensing:",
      "",
      "- Automatic firearms",
      "- Heavy weapons",
      "- Light machine guns (LMGs)",
      "- Armor-piercing (AP) weapons",
      "- Explosive weapons",
      "- Anti-vehicle weapons",
      "- Military-grade firearms",
      "- Weapons designed for mass casualty use",
      "- Unauthorized corporate or government weapons",
      "",
      "Weapons stolen from the NCPD, corporations, government agencies, or military organizations are illegal to possess unless legally recovered and registered.",
      "",
      "**Section 2.04 — Firearm Use and Discharge**",
      "",
      "A firearm may only be discharged for:",
      "",
      "- Lawful self-defense",
      "- Defense of another person",
      "- Authorized security operations",
      "- Law-enforcement operations",
      "- Licensed training or firing ranges",
      "",
      "Reckless discharge, unnecessary warning shots, firing in crowded areas, or using a firearm to intimidate another person is prohibited.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 3 — Controlled Drugs and Narcotics",
    body: [
      "**Section 3.01 — Legal Drug Use**",
      "",
      "Many recreational, medical, and performance-enhancing substances are legal in Night City when manufactured, distributed, and used according to law.",
      "",
      "A person must be at least 19 YoA to purchase, possess, or consume recreational drugs.",
      "",
      "**Section 3.02 — Drug Manufacturing and Distribution**",
      "",
      "Businesses manufacturing, selling, or distributing controlled substances must possess the required permits.",
      "",
      "Drug products must include accurate labeling, safety information, and warnings regarding known risks.",
      "",
      "The sale, production, or distribution of contaminated, poisoned, falsely labeled, or intentionally harmful substances is prohibited.",
      "",
      "**Section 3.03 — Illegal Drug Use**",
      "",
      "Drug use becomes unlawful when it creates a danger to others, including:",
      "",
      "- Operating vehicles while impaired",
      "- Operating dangerous machinery while impaired",
      "- Performing medical, security, or emergency duties while impaired",
      "- Secretly administering drugs to another person",
      "- Using substances in restricted emergency areas",
      "",
      "Night City authorities may prohibit substances considered extremely dangerous, weaponized, contaminated, or connected to a public-health emergency.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 4 — Braindances",
    body: [
      "**Section 4.01 — Legal Braindances**",
      "",
      "Braindances may be created, sold, purchased, possessed, and experienced when produced and distributed legally.",
      "",
      "Age-restricted Braindances require the user to be at least 19 YoA.",
      "",
      "**Section 4.02 — Prohibited Extreme Braindances**",
      "",
      "An Extreme Braindance, commonly called an XBD, is a sensory recording containing extreme violence, sexual content, trauma, pain, or dangerous experiences.",
      "",
      "All Extreme Braindances are illegal in Night City. The production, distribution, sale, purchase, possession, or use of an XBD is prohibited.",
      "",
      "An XBD includes any recording that contains:",
      "",
      "- Real murder",
      "- Sexual assault",
      "- Forced participation",
      "- Kidnapping",
      "- Torture",
      "- Human trafficking",
      "- Abuse of a minor",
      "- Any other serious criminal act",
      "",
      "Secretly recording another person's memories, neural data, or private experiences is prohibited.",
      "",
      "Possession or distribution of illegal XBD material may result in confiscation, arrest, criminal charges, and additional penalties under applicable law.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 5 — Gambling",
    body: [
      "**Section 5.01 — Licensed Gambling**",
      "",
      "Gambling is legal through licensed casinos, clubs, betting services, and approved digital platforms.",
      "",
      "A person must be at least 19 YoA to participate in commercial gambling.",
      "",
      "Licensed gambling businesses must clearly display:",
      "",
      "- Rules of play",
      "- Odds and probabilities",
      "- Costs and fees",
      "- Available payouts",
      "",
      "**Section 5.02 — Gambling Offenses**",
      "",
      "The following are prohibited:",
      "",
      "- Rigging games",
      "- Altering odds after wagers are placed",
      "- Fraudulent betting systems",
      "- Theft of customer funds",
      "- Refusal to provide lawful payouts",
      "- Forced gambling",
      "",
      "Gambling debts may be legally collected. However, debt collection may not involve assault, kidnapping, torture, threats, or unlawful coercion.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 6 — Sex Work and Adult Services",
    body: [
      "**Section 6.01 — Legal Sex Work**",
      "",
      "Consensual sex work is legal when all participants are at least 19 YoA and all required permits and licenses are maintained.",
      "",
      "Sex workers may operate independently or through licensed businesses, including:",
      "",
      "- Clubs",
      "- Hotels",
      "- Studios",
      "- Escort services",
      "- Adult entertainment establishments",
      "",
      "**Section 6.02 — Consent Requirements**",
      "",
      "Consent must be freely given and may be withdrawn at any time.",
      "",
      "Payment does not remove a person's right to refuse or stop an interaction.",
      "",
      "A person cannot legally consent while unconscious, severely impaired, threatened, restrained, or unable to understand the situation.",
      "",
      "**Section 6.03 — Prohibited Conduct**",
      "",
      "The following are illegal:",
      "",
      "- Human trafficking",
      "- Forced sex work",
      "- Sexual assault",
      "- Coercion",
      "- Secret recording of sexual activity",
      "- Violence or threats used to control workers",
      "",
      "Licensed businesses must provide reasonable safety measures for workers and customers.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 7 — Alcohol Regulation",
    body: [
      "**Section 7.01 — Alcohol Sales and Consumption**",
      "",
      "Alcohol is legal to manufacture, sell, possess, and consume in Night City.",
      "",
      "A person must be at least 19 YoA to purchase, possess, or consume alcohol.",
      "",
      "Businesses selling alcohol must maintain the proper licenses.",
      "",
      "**Section 7.02 — Alcohol Restrictions**",
      "",
      "Selling alcohol to a person under 19 YoA is prohibited.",
      "",
      "Businesses may refuse service to customers who are violent, threatening, or dangerously intoxicated.",
      "",
      "Public alcohol consumption may be restricted in designated areas. Alcohol may be prohibited in:",
      "",
      "- Government buildings",
      "- Police facilities",
      "- Medical facilities",
      "- Schools",
      "- Public transportation",
      "- Corporate restricted areas",
      "- Emergency zones",
      "",
      "Intoxication alone is not a crime. However, intoxication does not excuse unlawful actions.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 8 — Permits, Licenses, and Business Responsibilities",
    body: [
      "**Section 8.01 — Required Authorization**",
      "",
      "Any person or business involved in regulated goods or services must obtain the required permits, licenses, and registrations.",
      "",
      "Permits must be presented when lawfully requested by:",
      "",
      "- NCPD officers",
      "- City inspectors",
      "- Court officials",
      "- Authorized regulatory agencies",
      "",
      "**Section 8.02 — Permit Violations**",
      "",
      "A permit does not authorize:",
      "",
      "- Violence",
      "- Fraud",
      "- Theft",
      "- Trafficking",
      "- Coercion",
      "- Sales to minors",
      "- Reckless operation",
      "",
      "Permits may be suspended or revoked for:",
      "",
      "- Repeated violations",
      "- False applications",
      "- Criminal activity",
      "- Public safety threats",
    ].join("\n"),
  },
  {
    title: "NCMC Section 9 — Corporate Property Rules",
    body: [
      "**Section 9.01**",
      "",
      "Corporations may establish additional rules on property they legally control.",
      "",
      "Activities permitted under general Night City law may still be restricted inside:",
      "",
      "- Corporate buildings",
      "- Corporate facilities",
      "- Corporate vehicles",
      "- Controlled corporate districts",
      "",
      "Corporate restrictions generally do not apply outside recognized corporate property or authority.",
      "",
      "Visitors are responsible for following clearly posted corporate rules.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 10 — Emergency Restrictions",
    body: [
      "**Section 10.01**",
      "",
      "During major emergencies, Night City authorities may temporarily restrict certain activities.",
      "",
      "Emergency restrictions may affect:",
      "",
      "- Firearm sales or possession",
      "- Alcohol sales",
      "- Drug distribution",
      "- Gambling operations",
      "- Public gatherings",
      "- Travel",
      "- Business operations",
      "",
      "Emergency orders must identify the affected area, restrictions imposed, and expected duration.",
    ].join("\n"),
  },
  {
    title: "NCMC Section 11 — Enforcement and Penalties",
    body: [
      "**Section 11.01**",
      "",
      "Violations of this code may result in:",
      "",
      "- Warnings",
      "- Fines",
      "- Confiscation of illegal goods",
      "- Permit suspension",
      "- Business closure",
      "- Detention",
      "- Arrest",
      "- Criminal prosecution",
      "",
      "The classification and severity of offenses are determined under the Night City Infractions, Misdemeanors, and Felonies Code.",
    ].join("\n"),
  },
];

async function main() {
  const { db, ncpdLaws } = await import("@workspace/db");
  const { eq } = await import("drizzle-orm");

  let created = 0;
  let updated = 0;
  for (let i = 0; i < LAWS.length; i++) {
    const entry = LAWS[i];
    const sortOrder = i * 10;
    const [existing] = await db.select().from(ncpdLaws).where(eq(ncpdLaws.title, entry.title));
    if (existing) {
      await db
        .update(ncpdLaws)
        .set({ body: entry.body, sortOrder })
        .where(eq(ncpdLaws.id, existing.id));
      updated++;
      console.log(`  updated: ${entry.title}`);
    } else {
      await db.insert(ncpdLaws).values({ title: entry.title, body: entry.body, sortOrder });
      created++;
      console.log(`  created: ${entry.title}`);
    }
  }
  console.log(`\nDone. ${created} created, ${updated} updated (${LAWS.length} total).`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Law book import failed:", err);
  process.exit(1);
});
