import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import charactersRouter from "./characters";
import directoryRouter from "./directory";
import storesRouter from "./stores";
import fixerRouter from "./fixer";
import missionsRouter from "./missions";
import sheetsRouter from "./sheets";
import pendingEditsRouter from "./pending-edits";
import diceRouter from "./dice";
import adminRouter from "./admin";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import housingRouter from "./housing";
import lifestyleRouter from "./lifestyle";
import attendanceRouter from "./attendance";
import requestsRouter from "./requests";
import offersRouter from "./offers";
import loreRouter from "./lore";
import reviewRouter from "./review";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(charactersRouter);
router.use(directoryRouter);
router.use(storesRouter);
router.use(fixerRouter);
router.use(missionsRouter);
router.use(sheetsRouter);
router.use(pendingEditsRouter);
router.use(diceRouter);
router.use(adminRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(housingRouter);
router.use(lifestyleRouter);
router.use(attendanceRouter);
router.use(requestsRouter);
router.use(offersRouter);
router.use(loreRouter);
router.use(reviewRouter);

export default router;
