// One-off: copy membership_events + ingest cursors from dev DB to the LIVE prod DB.
// Additive + idempotent: CREATE TABLE IF NOT EXISTS, ON CONFLICT DO NOTHING,
// monotonic cursor upsert. Safe to re-run.
import pg from "pg";

const SRC = process.env.DATABASE_URL;
const DST = process.env.LIVE_PROD_DATABASE_URL;
if (!SRC || !DST) {
  console.error("Missing DATABASE_URL or LIVE_PROD_DATABASE_URL");
  process.exit(1);
}

const src = new pg.Pool({ connectionString: SRC, max: 2 });
const dst = new pg.Pool({ connectionString: DST, max: 2 });
src.on("error", (e) => console.error("src pool idle error", e.message));
dst.on("error", (e) => console.error("dst pool idle error", e.message));

async function main() {
  // Safety: confirm destination is the Neon live DB, not dev.
  const host = new URL(DST!).hostname;
  if (!host.includes("neon.tech")) {
    throw new Error(`Refusing: LIVE_PROD_DATABASE_URL host looks wrong: ${host}`);
  }
  console.log("target host:", host);

  await dst.query(`
    CREATE TABLE IF NOT EXISTS membership_events (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      source text NOT NULL,
      direction text NOT NULL,
      subject_id text NOT NULL,
      display_name text,
      occurred_at timestamptz NOT NULL,
      event_type text,
      source_ref text NOT NULL,
      created_at timestamptz NOT NULL DEFAULT now()
    );
    CREATE UNIQUE INDEX IF NOT EXISTS membership_events_ref_idx ON membership_events (source_ref);
    CREATE INDEX IF NOT EXISTS membership_events_src_time_idx ON membership_events (source, occurred_at);
    CREATE INDEX IF NOT EXISTS membership_events_subject_idx ON membership_events (subject_id, occurred_at);
  `);

  const { rows } = await src.query(
    `SELECT source, direction, subject_id, display_name, occurred_at, event_type, source_ref, created_at
     FROM membership_events ORDER BY id`
  );
  console.log(`source rows: ${rows.length}`);

  let inserted = 0;
  const BATCH = 500;
  for (let i = 0; i < rows.length; i += BATCH) {
    const chunk = rows.slice(i, i + BATCH);
    const vals: unknown[] = [];
    const tuples = chunk
      .map((r, j) => {
        const b = j * 8;
        vals.push(r.source, r.direction, r.subject_id, r.display_name, r.occurred_at, r.event_type, r.source_ref, r.created_at);
        return `($${b + 1},$${b + 2},$${b + 3},$${b + 4},$${b + 5},$${b + 6},$${b + 7},$${b + 8})`;
      })
      .join(",");
    const res = await dst.query(
      `INSERT INTO membership_events (source, direction, subject_id, display_name, occurred_at, event_type, source_ref, created_at)
       VALUES ${tuples} ON CONFLICT (source_ref) DO NOTHING`,
      vals
    );
    inserted += res.rowCount ?? 0;
  }
  console.log(`inserted: ${inserted}`);

  // Copy channel-walk cursors so the prod cron resumes instead of re-walking
  // ~250k messages. Monotonic upsert: never move a cursor backwards.
  const cursors = await src.query(
    `SELECT key, value FROM bot_config WHERE key LIKE 'membership_cursor_%'`
  );
  for (const c of cursors.rows) {
    const id = typeof c.value === "object" && c.value !== null ? c.value.id : String(c.value);
    await dst.query(
      `INSERT INTO bot_config (key, value) VALUES ($1, $2::jsonb)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
       WHERE coalesce(bot_config.value ->> 'id', bot_config.value #>> '{}')::numeric
           < coalesce(EXCLUDED.value ->> 'id', EXCLUDED.value #>> '{}')::numeric`,
      [c.key, JSON.stringify({ id })]
    );
    console.log(`cursor ${c.key} -> ${id}`);
  }

  const check = await dst.query(
    `SELECT source, direction, count(*)::int AS n, min(occurred_at) AS min, max(occurred_at) AS max
     FROM membership_events GROUP BY 1, 2 ORDER BY 1, 2`
  );
  console.table(check.rows);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
